services:
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
      target: prod
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - .:/app

