services:
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
      target: dev
    volumes:
      - .:/app

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog.${APP_NAMESPACE}
    ports:
      - "8003:1025"
      - "8100:8025"
    networks:
      - app
