services:
  php:
    command: ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog.${APP_NAMESPACE}
    ports:
      - "8003:1025"
      - "8100:8025"
    networks:
      - app
